### ISSUE TITLE
Add support for F1 2019

### ISSUE THREAD

**Issue by codegefluester** [jonybur/f1-telemetry-client#10]
F1 2019 is due to be released in about a week or so hence filing this issue to track any changes that need to be done to support F1 2019 (assuming that there will be changes).

- [x] Assess changes that need to be made for F1 2019
- [x] Agree on a proper design to support both versions of the game
- [x] Update code and tests according to the new design specs

**Comment by codegefluester** [comment]
The UDP specs are live and there have been a few changes, especially the packet header changed and includes version fields now https://forums.codemasters.com/topic/38920-f1-2019-udp-specification/

**Comment by jonybur** [comment]
I will be adding support for F1 2019 ASAP (hopefully in around two weeks time)
