### ISSUE TITLE
Normalise values for throttle/brake/steering

### ISSUE THREAD

**Issue by codegefluester** [jonybur/f1-telemetry-client#18]
**Is your feature request related to a problem? Please describe.**
The 2018 format uses a range from 0-100 for throttle, brake and steering while the 2019 format uses a range from 0 - 1.0.

**Describe the solution you'd like**
Normalise the values so developers only need to deal with one range, either 0-100 or 0.0 - 1.0 by handling this at the library level.

**Describe alternatives you've considered**
- Each application handles it on their own and normalises the values if it supports both game version. No change at the library level.
- Instead of always normalising the values one or the other way, introduce a setting where developers can opt-in to this behaviour/chose the kind of range they want.
- Convince Codemasters to settle on a single range, which would then probably be 0-100 since that is what the 2018 game used.

**Comment by jonybur** [comment]
I've noticed the same thing. I don't want to change the behavior/ranges of the telemetry information from the client - since that will mean opinionating the data from our end.
A possible fix could be adding a flag such as `--normalizedValues` or so.
Thank you for your input.

**Comment by codegefluester** [comment]
That's fair. I'm fine with handling this on my end in any case. Mostly surprised that Codies didn't stick to the same format :(
