### ISSUE TITLE
Format of m_wheelSlip/m_wheelSpeed changed from array of floats to array of objects

### ISSUE THREAD

**Issue by codegefluester** [jonybur/f1-telemetry-client#19]
**Describe the bug**
While still an array, the data format that the client sends for wheel slip and wheel speed changed the format. Previously the data was a simple `array` of `float` values. In `v0.1.10` it changed to an array of objects.

```
// Before
m_wheelSlip = [0,0,0,0]

// After
m_wheelSlip = [
  { m_wheelSlip: 0},
  { m_wheelSlip: 0},
  { m_wheelSlip: 0},
  { m_wheelSlip: 0},
]
```

This change does not seem intentional to me and also makes the format a bit more complicated than it has to be IMO.

**To Reproduce**
```
const { F1TelemetryClient, constants } = require("f1-telemetry-client");
const { PACKETS } = constants;

const client = new F1TelemetryClient();
client.on(PACKETS.motion, m => console.log(m.m_wheelSlip﻿));
```

**Expected behavior**
The data should be a simple `array` of `floats`

**Comment by jonybur** [comment]
Hi @codegefluester ,

Thank you for your input. This was not changed in 0.1.10, but it has been like this for several versions now. I will make this change for the v0.1.11 release.

**Comment by codegefluester** [comment]
Cheers, I think I just put v0.1.10 since that is what I'm currently on and I didn't use the previous version as much as today.

Thanks for all your work on this!
- Bjorn

**Comment by jonybur** [comment]
No problem Bjorn. I am merging `v0.1.11` right now, which fixes this behavior. Thanks again.
