### ISSUE TITLE
Class F1TelemetryClient extends the EventEmitter namespace

### ISSUE THREAD

**Issue by DerkJanSpeelman** [jonybur/f1-telemetry-client#27]
I made a pullrequest as well: https://github.com/jonybur/f1-telemetry-client/pull/29. But, this pullrequest also contains 64-bit unsigned integer support for the `m_sessionUID` in the `PacketHeader`.

**The F1TelemetryClient extends the EventEmitter namespace.** This gives my project the following errors:

**server/index.ts**:
```
client.on(PACKETS.session, console.log);
// error: Property 'on' does not exist on type 'F1TelemetryClient'. ts(2339)
```
![Property 'on' does not exist on type 'F1TelemetryClient'](https://user-images.githubusercontent.com/14921446/73895887-6d4d8780-4881-11ea-9a31-ef0c18d8c7d4.png)

**f1-telemetry-client\build\src\index.d.ts**:
```
declare class F1TelemetryClient extends EventEmitter {
// error: Type 'typeof EventEmitter' is not a constructor function type. ts(2507)
```
![Type 'typeof EventEmitter' is not a constructor function type](https://user-images.githubusercontent.com/14921446/73895960-a71e8e00-4881-11ea-979f-db4af6e2fe84.png)

<br>

**How to Reproduce:**

`npm init`
`npm i typescript ts-node-dev f1-telemetry-client`
`npm i @types/node -D`

**server/index.ts**:
```
import { F1TelemetryClient, constants } from 'f1-telemetry-client';
const { PACKETS } = constants;

const client: F1TelemetryClient = new F1TelemetryClient();

client.on(PACKETS.session, console.log);
//     ^ error
client.on(PACKETS.motion, console.log);
client.on(PACKETS.lapData, console.log);
client.on(PACKETS.event, console.log);
client.on(PACKETS.participants, console.log);
client.on(PACKETS.carSetups, console.log);
client.on(PACKETS.carTelemetry, console.log);
client.on(PACKETS.carStatus, console.log);

// start
client.start();

// stop:
[`exit`,
 `SIGINT`,
 `SIGUSR1`,
 `SIGUSR2`,
 `uncaughtException`,
 `SIGTERM`,
].forEach(eventType => {
  (process as NodeJS.EventEmitter).on(eventType, () => client.stop());
});
```

**server/tsconfig.json**:
```
{
    "compilerOptions": {
        "module": "commonjs",
        "outDir": "../dist/server",
        "strictNullChecks": true,
        "esModuleInterop": true,
    },
    "exclude": [
        "node_modules"
    ],
}
```

**Comment by jonybur** [comment]
Thank you for your issue & PR @DerkJanSpeelman; will check both of them ASAP.

**Comment by jonybur** [comment]
Your PR has been merged and published @DerkJanSpeelman , thank you for your help 🥇 👍👍👍
