### ISSUE TITLE
Add support for F2 2019

### ISSUE THREAD

**Issue by QuozPowa** [jonybur/f1-telemetry-client#34]
Hello
I notice that F2 2019 Teams are not available in the TEAMS file. Would it be possible to include them ? 

Updated specification is available here :
https://forums.codemasters.com/topic/44592-f1-2019-udp-specification/

You can duplicate my fork https://github.com/QuozPowa/f1-telemetry-client/blob/dd12b1d3c4d75b7a73fdd4086808642c61c053b6/src/constants/teams.ts but I don't have official hex colors....

**Comment by QuozPowa** [comment]
I think there is also a mismatch with tyre specification (information provided on the Codemasters thread and information provided in the game F1 2019).

**Comment by jonybur** [comment]
Thank you @QuozPowa will be working on this in the upcoming days.
